on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      version:
        description: 'Provide release tag, eg. 0.5.4'
        type: string
        required: true
        
permissions:
  contents: write
    
env:
  VERSION: ${{ inputs.version }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

run-name: Build tezuka_fw run for tag - Tezuka_${{ inputs.version }}
jobs:
  build-x86_64:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # environment: plutosdr-fw-ci
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        clean: false
        submodules: recursive

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -y make gcc g++ python3 python3-dev python3-pip \
           python3-pytest python3-numpy python3-scipy iverilog wget curl \
           default-jre libxrender-dev libxtst-dev libtinfo5 \
           libgtk2.0-0 git \
           zip unzip dfu-util fakeroot u-boot-tools device-tree-compiler mtools \
           bison flex libncurses5-dev libssl-dev bc cpio rsync cmake \
           libgtk-3-0 xz-utils libgmp-dev libmpc-dev bootgen-xlnx libclang-dev
           
      
           
    - name: Build Tezuka 
      run: |
        source sourceme.first
        mkdir ${{runner.workspace}}/build && cd ${{runner.workspace}}/build
        wget https://buildroot.org/downloads/buildroot-2024.08.tar.gz && tar -xvf buildroot-2024.08.tar.gz
       
        cd  ${{runner.workspace}}/build/buildroot-2024.08
        make pluto_maiasdr_defconfig && make && mv ${{runner.workspace}}/build/buildroot-2024.08/output/images/tezuka.zip ${{runner.workspace}}/build/pluto.zip
        rm -rf ${{runner.workspace}}/build/buildroot-2024.08/output/images
        make plutoplus_maiasdr_defconfig && make uboot-dirclean && make linux-dirclean && make && mv ${{runner.workspace}}/build/buildroot-2024.08/output/images/tezuka.zip ${{runner.workspace}}/build/plutoplus.zip
        rm -rf ${{runner.workspace}}/build/buildroot-2024.08/output/images
        make e200_maiasdr_defconfig && uboot-dirclean && make linux-dirclean && make && mv ${{runner.workspace}}/build/buildroot-2024.08/output/images/tezuka.zip ${{runner.workspace}}/build/antsdr_e200.zip
        rm -rf ${{runner.workspace}}/build/buildroot-2024.08/output/images
        make libre_maiasdr_defconfig && uboot-dirclean && make linux-dirclean && make && mv ${{runner.workspace}}/build/buildroot-2024.08/output/images/tezuka.zip ${{runner.workspace}}/build/libresdr.zip
       
    - name: Save zip Archive
      uses: actions/upload-artifact@v4
      with:
          name: tezuka_fw
          path: ${{runner.workspace}}/build/*.zip

  create_full_archive:
    needs: ['build-x86_64']
    runs-on: ubuntu-latest

    steps:
    - name: Download All Builds
      uses: actions/download-artifact@v4

    - name: Create Archive
      run: >
        mkdir tezuka_all && 
        mv tezuka_fw/*.zip tezuka_all/  
        
        
    - uses: actions/upload-artifact@v4
      with:
        name: tezuka_all
        path: tezuka_all/

  update_nightly_release:
          needs: [create_full_archive]
          runs-on: ubuntu-latest
        

          steps:
          - name: Download All Builds
            uses: actions/download-artifact@v4

          - name: Update Nightly
            run: gh release create ${{ inputs.version }} tezuka_all/* -R ${{github.repository}} --generate-notes
 