on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      version:
        description: 'Provide release tag, eg. 0.5.4'
        type: string
        required: true
        
permissions:
  contents: write
    
env:
  VERSION: ${{ inputs.version }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

run-name: Build tezuka_fw run for tag - Tezuka_${{ inputs.version }}
jobs:
  build-x86_64:
    # runs-on: self-hosted
    runs-on: ubuntu-22.04
    # environment: plutosdr-fw-ci
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        clean: false
        fetch-depth: 0
    - name: Free Disk Space Before Build
      run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
          echo "Disk space after cleanup:"
          df -h    
          
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -y make gcc g++ python3 python3-dev python3-pip \
           python3-pytest python3-numpy python3-scipy iverilog wget curl \
           default-jre libxrender-dev libxtst-dev libtinfo5 \
           libgtk2.0-0 git \
           zip unzip dfu-util fakeroot u-boot-tools device-tree-compiler mtools \
           bison flex libncurses5-dev libssl-dev bc cpio rsync cmake \
           libgtk-3-0 xz-utils libgmp-dev libmpc-dev bootgen-xlnx libclang-dev
           
      
           
    - name: Build Tezuka 
      run: |
        source sourceme.first
        ./getbuildroot.sh

        mkdir ${{runner.workspace}}/build && cd ${{runner.workspace}}/build
        wget -O- https://buildroot.org/downloads/buildroot-2025.05.tar.gz | tar -xz --one-top-level=buildroot --strip-components=1
               
        cd  ${{runner.workspace}}/build/buildroot
        make pluto_maiasdr_defconfig && make && mv ${{runner.workspace}}/build/buildroot/output/images/tezuka.zip ${{runner.workspace}}/build/pluto.zip
        make plutoplus_maiasdr_defconfig && make uboot-reconfigure && make linux-reconfigure && make maia-kmod-reconfigure && make && mv ${{runner.workspace}}/build/buildroot/output/images/tezuka.zip ${{runner.workspace}}/build/plutoplus.zip
        make e200_maiasdr_defconfig && make uboot-reconfigure && make linux-reconfigure && make maia-kmod-reconfigure && make && mv ${{runner.workspace}}/build/buildroot/output/images/tezuka.zip ${{runner.workspace}}/build/antsdr_e200.zip
        make libre_maiasdr_defconfig  && make uboot-reconfigure && make linux-reconfigure && make maia-kmod-reconfigure && make && mv ${{runner.workspace}}/build/buildroot/output/images/tezuka.zip ${{runner.workspace}}/build/libresdr.zip
        make fishball_maiasdr_defconfig  && make uboot-reconfigure && make linux-reconfigure && make maia-kmod-reconfigure &&  make && mv ${{runner.workspace}}/build/buildroot/output/images/tezuka.zip ${{runner.workspace}}/build/fishball.zip
        make fishball_maiasdr_7020_defconfig  && make uboot-reconfigure && make linux-reconfigure && make maia-kmod-reconfigure && make && mv ${{runner.workspace}}/build/buildroot/output/images/tezuka.zip ${{runner.workspace}}/build/fishball7020.zip

    - name: Save zip Archive
      uses: actions/upload-artifact@v4
      with:
          name: tezuka_fw
          path: ${{runner.workspace}}/build/*.zip

  create_full_archive:
    needs: ['build-x86_64']
    runs-on: ubuntu-22.04

    steps:
    - name: Download All Builds
      uses: actions/download-artifact@v4

    - name: Create Archive
      run: >
        mkdir tezuka_all && 
        mv tezuka_fw/*.zip tezuka_all/  
        
        
    - uses: actions/upload-artifact@v4
      with:
        name: tezuka_all
        path: tezuka_all/

  update_nightly_release:
          needs: [create_full_archive]
          runs-on: ubuntu-22.04
        

          steps:
          - name: Download All Builds
            uses: actions/download-artifact@v4

          - name: Update Nightly
            run: gh release create ${{ inputs.version }} tezuka_all/* -R ${{github.repository}} --generate-notes
 